#+TITLE: Purne Linux Kernel
#+DATE: <2018-02-08 四>

: 这篇文章主要介绍如何裁剪和编译内核

** 裁剪内核

** 编译内核

   : 首先编译内核最基本的技能
   : 1. 能够看懂Makefile,最好能够全部看一遍,心里有个数.
   : 2. 如果不能,那就必须会使用make help 查看内核编译选项的各个功能说明.

*** kernle-makefile中的伪指令

*** 编译完整内核(全编)

*** 编译模块

**** 单独编译内核的模块

     之前肯定要编译过内核的,如果不是请编译完成的内核.

     来个例子:
     : make CONFIG_DRM_VMWGFX=m -C /home/dange/tmp/linux-4.8.0 M=/home/dange/tmp/linux-4.8.0/drivers/gpu/drm/vmwgfx modules
     
     简单的写:
     : make CONFIG_DEMO_TEST=m -C . M=drivers/char/ modules

*** 不基于源码,而基于内核树编译的方法

    : 这个和上面单编内核模块很像,只不过在外部而已,并且要自己实现一个makefile
    
**** 依赖内核树,在源码外构建模块的万能makefile
     
     #+BEGIN_SRC makefile
     ifneq ($(KERNELRELEASE),)
     obj-m := hello.o
     else
     KERNELDIR ?= /lib/modules/$(shell uname -r)/build
     PWD := $(shell pwd)
     default:
     $(MAKE) -C $(KERNELDIR) M=$(PWD) modules
     endif
     #+END_SRC

*** 编译内核可能遇到的问题总结
    
    Description: 当编译PC机的外挂模块的时候,默认会放到/lib/modules目录下的相应内核版本目录.
    而这个内核版本目录是可能被覆盖的,如当我们重复编译一个内核版本的时候,这样重新编译的时候可能有问题.
    Thinking: 可以使用鸟哥提供的方法,是先将老版本的内核输出备份一下,然后再编译
    mv 2.6.30 2.6.30.old

    Description: 如果感觉编译内核的时候没有办法达到你要的编译速度,如果是多核操作系统,可以使用多线程编译.
    Thinking: 具体方法就是make -jn 这里的n最好能够自己控制的.

** 好文章链接

   linux内核裁剪文件的解释:\\
   http://blog.csdn.net/a746742897/article/details/52247292\\

   linux makefile伪指令简单介绍:\\
   http://blog.csdn.net/leon1741/article/details/54846170\\
   http://blog.csdn.net/sidely/article/details/40296745\\

   linux关于menuconfig使用的介绍:\\
   http://blog.csdn.net/a746742897/article/details/52243980\\

