#+TITLE: Linux导航

: 这篇文档主要介绍的内容
#+BEGIN_EXAMPLE
0. 如何查看内核源码
1. 内核文档导航和切入的技巧
2. 内核代码定位的正则技巧和方法
3. 特定代码位置简介
4. 内核相关的辅助链接内容
#+END_EXAMPLE

** =Description := 如何查看内核源码?

***  _Thinking :_ 记录查看内核源代码技巧

    内核源码四法宝:
    1. 内核相关模块的文档 (详细的介绍)
    2. 相关模块的README (简单的介绍,如果有的话)
    3. 相关模块的Kconfig
    4. 相关模块的Makefile

** =Description := Linux源码查看切入点分析方法

*** _Thinking :_ 下面记录一下如何开始查看linux内核源码

    内核源码是很庞大的,就现在来看,那么在看一个工程的代码时,需要一定的技巧来看源码:
    1. 首先通过文档或者书籍了解相关模块的知识.
    2. 使用上面的如何查看内核源代码的技巧索引到想要分析的模块.
    3. 其次根据文档或者书籍找到模块的关键数据结构,主要分析
    4. 找到模块相关的头文件来分析数据结构相关的操作内容.

    : 需要的资料有
    内核文档,书籍,Kconfig makefile 头文件,最后是源文件.
 
** =Description := Linux内核代码正则索引定位技巧

*** _Thinking :_ 这个内容可能需要不停的更新,下面就是一些例子

    正则表达式的学习是很重要的,可以学习perl的正则,全面而优雅.
    
    使用正则的习惯事项注意:
    #+BEGIN_EXAMPLE
    括号索引需要反引 : \( \) \{ \}
    #+END_EXAMPLE

    系统调用的查询:
    : SYSCALL.*getpid

    内核符号导出的查询:
    : EXPORT.*sprintf\)
    

** =Description:= Linux特定代码位置简介

*** _Thinking :_ 内核中代码规划是有张可循的,所以仅以此记录

    linux代码中权能相关的列表位置:
    <linux/capability.h>

    linux系统调用号位置
    <asm/unistd.h>

    linux大部分系统调用源码的实现在:
    kernel/sys.c

    linux链表实现位置:
    <linux/list.h>
    
    linux队列的实现位置:
    <linux/kfifo.h>

    linux自旋锁是和特定体系结构相关的:
    <asm/spinlock.h>

    linux完成变量的定义在:
    <linux/completion.h>

    linux内核编译文档:
    Documentation/kbuild/

    编译内核的依赖工具文档位置:
    Documentation/Changes
    
** =Description := Linux话题相关链接

*** _Thinking :_ 记录linux内核常用链接

    内核主页:(一般这个就够了)
    https://www.kernel.org/

    内核文档搜索:
    https://www.kernel.org/doc/html/latest/search.html?q=exit_file&check_keywords=yes&area=default#

    嵌入式内核的wiki:
    https://elinux.org/Main_Page


    内核邮件列表:
    http://vger.kernel.org/

    Linux和BSD内核的技术新闻.如果没时间跟踪LKML,那么经常浏览kerneltrap是个好主意.
    http://kerneltrap.org

    Linux weekly news，创建于1997年底的一个Linux新闻站点。
    http://lwn.net/

    这是内核开发的中文邮件列表，里面活跃着很多内核开发领域的华人，比如Herbert Xu,、Mingming Cao、Bryan Wu等.(可能被禁了)
    http://zh-kernel.org/mailman/listinfo/linux-kernel

    全球最大的Linux/Unix中文技术社区(可能被禁了)
    http://linux.chinaunix.net/
